# Generated by Django 5.0.6 on 2024-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto_de_perfil',
            field=models.CharField(default="models.ImageField(upload_to='fotos_de_perfil/', blank=True, null=True)", max_length=100),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem_do_post',
            field=models.CharField(default="models.ImageField(upload_to='imagens_posts/', blank=True, null=True)", max_length=100),
        ),
    ]
