# Generated by Django 5.0.6 on 2024-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('avalie', models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('M', 'Mediano'), ('B', 'Bom'), ('E', 'Excelente')], max_length=5)),
                ('comentario', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
