# Generated by Django 5.0.6 on 2024-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='avalie',
            field=models.CharField(blank=True, choices=[('1', 'Péssimo'), ('2', 'Ruim'), ('3', 'Mediano'), ('4', 'Bom'), ('5', 'Excelente')], max_length=5, null=True),
        ),
    ]
