# Generated by Django 5.0.6 on 2024-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='galeria.tag'),
        ),
    ]
