# Generated by Django 5.0.6 on 2024-05-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_foto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='tags',
            field=models.ManyToManyField(to='galeria.tag'),
        ),
    ]
