# Generated by Django 5.0.6 on 2024-05-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_foto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
