# Generated by Django 5.0.6 on 2024-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_remove_foto_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
