# Generated by Django 5.0.6 on 2024-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('galeria', '0005_album_privado'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='usuario',
            field=models.ManyToManyField(to='core.usuario'),
        ),
    ]
