# Generated by Django 5.0.6 on 2024-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_conclusão', models.DateField()),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em Progresso'), ('CONCLUIDA', 'Concluída')], max_length=12)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
    ]
