# Generated by Django 5.0.6 on 2024-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='estado',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM PROGRESSO', 'Em Progresso'), ('CONCLUIDA', 'Concluída')], max_length=12),
        ),
    ]
