# Generated by Django 5.0.6 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tarefa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_inicio',
            field=models.DateField(help_text='xx/xx/xxxx...'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
