CREATE DATABASE exercicio2;


CREATE TABLE DEPARTAMENTO (
	ID_DEPARTAMENTO INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL
);


CREATE TABLE MARCA (
	ID_MARCA INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL
);


CREATE TABLE UNIDADE_MEDIDA (
	ID_UNIDADE_MEDIDA INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL
);


CREATE TABLE CATEGORIA (
	ID_CATEGORIA INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL,
	ID_DEPARTAMENTO INTEGER,
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);


CREATE TABLE SUBCATEGORIA (
	ID_SUBCATEGORIA INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(255) NOT NULL,
	ID_CATEGORIA INTEGER,
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);


CREATE TABLE PRECO_VENDA (
	ID_PRECO_VENDA INTEGER PRIMARY KEY,
	ID_PRODUTO INTEGER,
	PRD_PRECO_VENDA DECIMAL(10, 2) NOT NULL,
	DATA_VALIDADE_INICIAL DATE,
	DATA_VALIDADE_FINAL DATE,
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);


CREATE TABLE PRODUTO_SIMILAR (
	ID_PRODUTO INTEGER,
	ID_PRODUTO_SIMILAR INTEGER,
	PRIMARY KEY (ID_PRODUTO, ID_PRODUTO_SIMILAR),
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	FOREIGN KEY (ID_PRODUTO_SIMILAR) REFERENCES PRODUTO(ID_PRODUTO)
);


CREATE TABLE PRODUTO (
	ID_PRODUTO INTEGER PRIMARY KEY,
	CODIGO VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	ID_SUBCATEGORIA INTEGER,
	ID_MARCA INTEGER,
	ID_UNIDADE_MEDIDA INTEGER,
	ESPECIFICACAO_TECNICA VARCHAR(255),
	PRD_STATUS VARCHAR(50),
	PESO_BRUTO DECIMAL(10, 2),
	PESO_LIQUIDO DECIMAL(10, 2),
	QTD_MULT INTEGER,
	QTD_MIN INTEGER,
	COD_BARRA VARCHAR(50),
	FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIA(ID_SUBCATEGORIA),
	FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
	FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(ID_UNIDADE_MEDIDA)
);


INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, DESCRICAO)
VALUES (1, 'Tecnologia'), (2, 'Casa e Decoração');

INSERT INTO MARCA (ID_MARCA, DESCRICAO)
VALUES (1, 'Dell');


INSERT INTO UNIDADE_MEDIDA (ID_UNIDADE_MEDIDA, DESCRICAO)
VALUES (1, 'Unidade');

INSERT INTO CATEGORIA (ID_CATEGORIA, DESCRICAO, ID_DEPARTAMENTO)
VALUES (1, 'Eletrônicos', 1);


INSERT INTO SUBCATEGORIA (ID_SUBCATEGORIA, DESCRICAO, ID_CATEGORIA)
VALUES (1, 'Smartphones', 1), (2, 'Laptops', 2);


INSERT INTO PRECO_VENDA (ID_PRECO_VENDA, ID_PRODUTO, PRD_PRECO_VENDA, DATA_VALIDADE_INICIAL, DATA_VALIDADE_FINAL)
VALUES(1, 1, 8000.00, '2024-10-01', '2027-12-31');


INSERT INTO PRODUTO_SIMILAR (ID_PRODUTO, ID_PRODUTO_SIMILAR)
VALUES (1, 2);

INSERT INTO PRODUTO (ID_PRODUTO, CODIGO, DESCRICAO, ID_SUBCATEGORIA, ID_MARCA, ID_UNIDADE_MEDIDA, ESPECIFICACAO_TECNICA, PRD_STATUS, PESO_BRUTO, PESO_LIQUIDO, QTD_MULT, QTD_MIN, COD_BARRA)
VALUES (1, '001', 'Notebook Dell', 2, 1, 1, 'Intel Core i7, 16GB RAM, 512GB SSD', 'Ativo', 2.0, 1.8, 1, 10, '7891234567890');
