# Generated by Django 5.0.6 on 2024-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('rg', models.PositiveIntegerField()),
                ('passaporte', models.PositiveIntegerField(blank=True, null=True)),
                ('cnh', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
