# Generated by Django 5.0.6 on 2024-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='passaporte',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='primeiro_nome',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, null=True),
        ),
    ]
