# Generated by Django 5.0.6 on 2024-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_dadospessoais_cnh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
