# Generated by Django 5.0.6 on 2024-05-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_dadospessoais_data_nasc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='dadospessoais',
            name='sexo',
        ),
    ]
