# Generated by Django 5.0.6 on 2024-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturas', models.CharField(max_length=254)),
                ('recibos', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DocReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante_de_reserva', models.CharField(max_length=254)),
                ('termos_e_condicoes', models.TextField()),
            ],
        ),
    ]
