# Generated by Django 5.0.6 on 2024-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qua_numero', models.PositiveIntegerField()),
                ('qua_andar', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclui_ref', models.BooleanField()),
                ('desc_ref', models.CharField(max_length=254)),
                ('valor_ref', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor_servico', models.FloatField()),
                ('tipo_servico', models.CharField(max_length=254)),
                ('n_ocupantes', models.PositiveIntegerField()),
                ('res_entrada', models.DateTimeField()),
                ('res_saida', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='docreserva',
            old_name='comprovante_de_reserva',
            new_name='comprovante_reserva',
        ),
        migrations.RenameField(
            model_name='docreserva',
            old_name='termos_e_condicoes',
            new_name='termos_condicoes',
        ),
    ]
