# Generated by Django 5.0.6 on 2024-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_quarto_refeicao_servico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docreserva',
            options={'ordering': ('pk',), 'verbose_name': 'Reserva | Documento', 'verbose_name_plural': 'Reservas | Documentos'},
        ),
    ]
