# Generated by Django 5.0.6 on 2024-05-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_docreserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refeicao',
            options={'ordering': ('pk',), 'verbose_name': 'Refeição', 'verbose_name_plural': 'Refeições'},
        ),
    ]
