# Generated by Django 5.0.6 on 2024-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_refeicao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='tipo_ref',
            field=models.CharField(blank=True, choices=[('C', 'Café da Manhã'), ('A', 'Almoço'), ('J', 'Janta'), ('S', 'Serviço de Quarto'), ('T', 'Tudo Incluso')], max_length=5, null=True),
        ),
    ]
