# Generated by Django 5.0.6 on 2024-05-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_refeicao_tipo_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='inclui_ref',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='n_ocupantes',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='res_entrada',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='res_saida',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='valor_servico',
        ),
    ]
