# Generated by Django 5.0.6 on 2024-05-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='foto_de_perfil',
            new_name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
    ]
