# Generated by Django 5.0.6 on 2024-05-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='foto_perfil',
            new_name='foto',
        ),
    ]
