# Generated by Django 5.0.6 on 2024-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfil_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
