# Generated by Django 5.0.6 on 2024-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_perfil_cliente_alter_perfil_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
