# Generated by Django 5.0.6 on 2024-05-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_foto_ultima_modificacao_alter_albun_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albun',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='album',
        ),
        migrations.AddField(
            model_name='foto',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.albun'),
        ),
        migrations.AddField(
            model_name='foto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.usuario'),
        ),
    ]
