# Generated by Django 5.0.6 on 2024-05-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_remove_albun_foto_remove_usuario_album_foto_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albun',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.usuario'),
        ),
    ]
