# Generated by Django 5.0.6 on 2024-05-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_albun_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albun',
            new_name='Album',
        ),
    ]
