# Generated by Django 5.0.6 on 2024-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_rename_albun_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(default='Imagem', max_length=50),
        ),
    ]
