# Generated by Django 5.0.6 on 2024-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='faltas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='justificadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='presenca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='tipo',
            field=models.CharField(choices=[('F', models.PositiveIntegerField(default=0)), ('J', models.PositiveIntegerField(default=0)), ('P', models.PositiveIntegerField(default=0))], max_length=1),
        ),
    ]
