# Generated by Django 5.0.6 on 2024-05-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_remove_frequencia_quantidade_frequencia_faltas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.PositiveIntegerField()),
                ('justificadas', models.PositiveIntegerField()),
                ('presenca', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='faltas',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='justificadas',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='presenca',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='tipo',
            field=models.CharField(choices=[('F', 'Número de Faltas'), ('J', 'Faltas Justificadas'), ('P', 'Dias de Presença')], max_length=3),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(choices=[('1', 'John Doe'), ('2', 'Jane Doe'), ('3', 'Peter Jones')], on_delete=django.db.models.deletion.CASCADE, to='aluno.author')),
            ],
        ),
    ]
