# Generated by Django 5.0.6 on 2024-05-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_author_tipofrequencia_remove_frequencia_faltas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoFrequencia',
        ),
    ]
