# Generated by Django 5.0.6 on 2024-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_faltas_outros_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faltas',
            name='faltas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='outros',
            name='outro',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
