# Generated by Django 5.0.6 on 2024-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_alter_faltas_faltas_alter_outros_outro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faltas',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='frequencia',
            name='faltas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='justificadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='presenca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Outros',
        ),
    ]
