# Generated by Django 5.0.6 on 2024-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturas', models.CharField(max_length=254)),
                ('recibos', models.CharField(max_length=254)),
            ],
        ),
    ]
