# Generated by Django 5.0.6 on 2024-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_celular', models.PositiveIntegerField()),
                ('confirmacao_de_reserva', models.BooleanField()),
                ('receber_notificacoes', models.BooleanField()),
            ],
        ),
    ]
