# Generated by Django 5.0.6 on 2024-05-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0002_alter_cliente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='(aguardando descrição)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojinha.subcategoria'),
        ),
    ]
