# Generated by Django 5.0.6 on 2024-05-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0003_subcategoria_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria2',
            new_name='categoria_2',
        ),
    ]
