# Generated by Django 5.0.6 on 2024-05-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0004_rename_categoria2_produto_categoria_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_2',
        ),
        migrations.AddField(
            model_name='produto',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lojinha.subcategoria'),
        ),
    ]
