# Generated by Django 5.0.6 on 2024-05-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0005_remove_produto_categoria_2_produto_sub_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojinha.categoria'),
        ),
    ]
