# Generated by Django 5.0.6 on 2024-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor_produto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
