# Generated by Django 5.0.6 on 2024-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_valor_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valor_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_com_desc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_sem_desc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
